#!/bin/bash
set -eou pipefail

function main(){    
    local failed=""

    echo "Running: go vet"
    PACKAGES="$(go list ./... | grep 'rancher/security-scan')"
    go vet ${PACKAGES}

    echo "Running: golangci-lint"
    golangci-lint version
    golangci-lint run ./...

    echo "Running: go fmt"
    test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
}

main
