#!/bin/bash
set -eou pipefail

function main(){    
    local failed=""

    echo "Running: go vet"
    PACKAGES="$(go list ./... | grep 'rancher/security-scan')"
    go vet ${PACKAGES}

    echo "Running: golint"
    for i in ${PACKAGES}; do
        if [ -n "$(golint $i | grep -v 'should have comment.*or be unexported' | tee /dev/stderr)" ]; then
            failed=true
        fi
    done
    test -z "$failed"
    echo "Running: go fmt"
    test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
}

main
