#!/bin/bash
set -ex

source $(dirname $0)/version

cd $(dirname $0)/../cmd/kb-summarizer

mkdir -p bin
[ "$(uname)" != "Darwin" ] && LINKFLAGS="-extldflags -static -s"
CGO_ENABLED=0 go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o ../../bin/kb-summarizer
md5sum ../../bin/kb-summarizer